#+TITLE: rorg --- R and org-mode

Please feel free to change the layout of this file, I'm just putting
this here to get things started.

* notes

** objectives
First and foremost, what do we want to accomplish?

Just to get this out there, there seem to be four kinds of
functionality we're trying to get here:
1. import data into R from org
2. easy editing of R code using r-mode from an org buffer
3. evaluate R code and make the output available for processing in an
   org buffer
4. evaluate R code and format the output for export

** block types

Special editing and evaluation of source code in R blocks.
Unfortunately org-mode how two different block types.  Source code
blocks which look like the following allow for the special editing of
code inside of the block through `org-edit-special'.

#+begin_src R

#+end_src

dblocks, which look like the following allow for evaluation of the
code inside of the block by calling =\C-c\C-c= on the header of the
block.  This is handy, as org-mode will automatically call
`org-dblock-write:dblock-type' where dblock-type is the string
following the =#+BEGIN:= portion of the line.

#+BEGIN: dblock-type
#+END:

Note that upper and lower case are not relevant in block headings.

I'm leaning towards using the =#+begin_src= blocks, as that is really
what these blocks contain is source code.

* tasks

* buffer dictionary
 LocalWords:  DBlocks dblocks
