
#+TITLE:     Org-Mode Homepage
#+LANGUAGE:  en
#+EMAIL:     carsten at orgmode dot org
#+OPTIONS:   H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:t *:t TeX:t

* Org - an Emacs Mode for Notes and Project Planning

#+HTML:  <BASE href="http://orgmode.org/index.html">

Org-mode is a mode for keeping notes, maintaining ToDo lists, and doing
project planning with a fast and effective plain-text system.

Org-mode develops organizational tasks around NOTES files that contain
information about projects as plain text.  Org-mode is implemented on
top of outline-mode, which makes it possible to keep the content of
large files well structured.  Visibility cycling and structure editing
help to work with the tree.  Tables are easily created with a built-in
table editor.  Org-mode supports ToDo items, deadlines, time stamps,
and scheduling.  It dynamically compiles entries into an agenda.
Plain text URL-like links connect to websites, emails, Usenet
messages, BBDB entries, and any files related to the projects.  For
printing and sharing of notes, an Org-mode file can be exported as a
structured ASCII file, HTML, and LaTeX.

* Current Version (6.05) and Compatibility

The current version is 6.05.  To see what has changed in recent
releases, check this [[file:Changes.html][list of user-visible changes]].  These descriptions
are extensive, to avoid that people will be printing the manual after
each incremental release.  If you have an older version of the manual,
just check the release notes and you will be up-to-date.

This package works on Emacs 23 and 22, and (with minor restrictions)
on Emacs 21 and XEmacs 21 (where you must also use
/xemacs/noutline.el/ shipped with Org-mode).  The Emacs 22.2 release
ships with Org-mode version 4.67d.  The latest CVS emacs trunk usually
contains a fairly recent version, but may lag a bit behind the website
release.

* Downloads

** The standard distribution

Download as [[file:org-6.05.zip][zip file]] or [[file:org-6.05.tar.gz][gzipped tar archive]].  These archives contain
both the Lisp file org.el and the documentation in PDF and (TeX)Info
formats.  A shell script to simplify upgrading to the newest release
has been posted [[http://www.philfam.co.uk/pete/GTD/org-mode/update-org.sh][here]].

** The development version

You can check out the latest Org development version (along with every
release we ever had) by using git.  More information on this page:
http://repo.or.cz/w/org-mode.git

** Alternative distributions

   There are several alternative distrbutions of Org:

   - The [[http://savannah.gnu.org/cvs/%3Fgroup%3Demacs][Emacs CVS]] contains a recent version
   - The Debian packages are planned.
   - Mark A. Hershberger has made some [[https://launchpad.net/~hexmode/+archive][Ubuntu packages]] for Org, but
     these seem to be out of date.

* Documentation
** Manual and Reference card
   - Read the documentation [[file:manual/index.html][online]].  This is a version consisting of many
     small files, to save bandwidth.  If you really need it, you can also
     have the entire manual in a [[file:org.html][single monolithic file]].
   - Download the documentation in other formats: [[file:org.pdf][PDF]], [[file:org][Info]], or [[file:org.texi][TeXInfo]].
   - Download the [[file:orgcard.pdf][Refcard]] for org-mode, and Kyle Sherman hast created a
     [[file:orgcard.txt][text version]] of the reference card
   - There is also a [[http://hpcgi1.nifty.com/spen/index.cgi?OrgMode%2fManual][Japanese translation]] of the manual (version 4.60),
     produced by Takeshi Okano.
   - The [[http://orgmode.org/worg/org-faq.php][Org Mode FAQ]] is
     maintained by the Worg project.
   - The Org manual is a GNU Manual released under the GFDL.  If you
     want to redistribute Org with a distribution that does not allow
     the GFDL to be used, and if you see no other way to resolve this
     licensing conflict, you must use the special [[file:org_dual_license.texi][dual-license version]]
     of the manual.

* Links

** Mailing list

   There is a mailing list for discussion about org-mode.

   - Subscribe to it at [[http://lists.gnu.org/mailman/listinfo/emacs-orgmode][this webpage]].
   - Directly [[mailto:emacs-orgmode@gnu.org][send mail to it]].  If you are not subscribed, a moderator
     will look at the message before passing it through to the
     list.  If that has happened once, future messages from your email
     address will get through immediately, even if you remain
     unsubscribed.
   - Read the list on [[http://www.gmane.org][Gmane]] through a [[http://news.gmane.org/gmane.emacs.orgmode][web interface]] or with a
     [[news://news.gmane.org/gmane.emacs.orgmode][newsreader]].

#+BEGIN_HTML
<li><form method="get" action="http://search.gmane.org/">
<input type="text" name="query">
<input type="hidden" name="group" value="gmane.emacs.orgmode">
<input type="submit" value="Search gmane.emacs.orgmode">
</form>
#+END_HTML

** Worg - user-driven knowledge-base about org-mode

[[http://orgmode.org/worg/][Worg]], created by [[http://www.cognition.ens.fr/~guerry/][Bastien Guerry]], is a setup to allow users to jointly
edit a number of Org-mode files containing documentation about
Org-mode.  This is something like a wiki, but with the advantage that
you do not have to be online to modify a file.  If you'd like to
contribute your own setup, screenshots, tutorials etc, please go to
[[http://orgmode.org/worg/][the Worg page]], and start from there.

** Tutorials

   [[http://orgmode.org/worg/org-tutorials/index.php][Tutorials and screencasts]] are maintained by the [[http://orgmode.org/worg][Worg project]].

** Survey

   In November 2007, Charles Cave organized a survey among Org-mode
   users.  The answers given in this survey can be found [[file:survey.html][here]].

** Org-mode, GTD and other task management systems 
    Org-mode is flexible enough to implement many different ways of
    organizing your projects.  For links and pointers in this area,
    see the [[http://orgmode.org/worg/org-gtd-etc.php][Worg page dedicated to task management systems]].

** Contributing to Org-mode

   You can always contribute with ideas and bug reports on the mailing
   list.  If you want to contribute a patch, code snippets, or a full
   add-on, this is very welcome too!  However, I can only make it an
   official part of Org-mode if you have signed the papers with the
   Free Software Foundation.  Org-mode is distributed as part of Emacs
   and must therefore adhere to strict rules about the copyright of
   all included material.  If this is what you want to do, [[file:request-assign-future.txt][here]] is the
   form that you have to fill in and send to the FSF.  After you
   received the final copy with signatures, please scan it and send
   the scan to the maintainer.

** Future Development

   Org-mode is still developing fast.  The best way to stay up-to-date
   is to join the mailing list where the changes are developed and
   discussed.

   Here is a loose [[file:todo.org][list of ideas]] that are still to be processed
   somehow, when I get to it...

** Related Software


  Make an interesting list here!!!!
   
  [[http://sachachua.com/wp/][Sacha Chua]] about [[http://sachachua.com/wp/2007/12/26/emacs-choosing-between-org-and-planner/][Choosing between Planner and Org]].
 
  
