#+Title:     Talks about Org-mode, by Carsten Dominik
#+AUTHOR:    Carsten Dominik
#+EMAIL:     carsten.dominik@gmail.com
#+DATE:      March 5, 2010
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:nil tags:not-in-toc

* Google Tech Talk

Here it the video of the [[http://research.google.com/video.html][Google Tech Talk]] about [[http://orgmode.org][Org-mode]] that I gave
on July 15th, 2008 on the Google campus in Mountain View, California.
Thanks to [[http://emacspeak.sourceforge.net/raman/][T.V. Raman]] and [[http://technical-dresese.blogspot.com/][Andrew Hyatt]] for being my hosts during my
stay.

If you'd like to see the video in higher quality, you can do so at the
[[http://youtube.com/watch%3Fv%3DoJTwQvgfgMM][youtube page]].  Click the "watch in high resolution" linkt directly
below the video frame.

#+BEGIN_HTML
<object width="425" height="349"><param name="movie" value="http://www.youtube.com/v/oJTwQvgfgMM&hl=en&fs=1&rel=0&border=1"></param><param name="allowFullScreen" value="true"></param><embed src="http://www.youtube.com/v/oJTwQvgfgMM&hl=en&fs=1&rel=0&border=1" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="349"></embed></object>
#+END_HTML

For projection purposes you can also download the slides as a [[file:Google-Tech-Talk-Org-mode.pdf][PDF file]]
file or as a [[file:Google-Tech-Talk-Org-mode.swf][flash movie]].  If you'd like to prepare your own talk
about Org-mode and want to use some of my slides, here are the [[file:Google-Tech-Talk-Org-mode-keynote.zip][Apple
keynote]] and [[file:Google-Tech-Talk-Org-mode.ppt][Microsoft Powerpoint]] versions of the talk.  I am making
all these files available under the [[http://creativecommons.org/licenses/by/3.0/][creative commons license]]
(attribution).

* Talk at MPI Cologne

On February 8, 2010, I gave a talk about Org-mode at the Max-Planck
Institute for Neurological Research in Cologne.  The Max-Planck
Gesellschaft kindly makes available a [[http://www.nf.mpg.de/orgmode/guest-talk-dominik.html][video recording]] of the talk.
Thanks to Stefan Vollmar for his invitation and hospitality during the
visit, and for an insane amount of work that was needed to get the
audio recording to a state where it at least can be understood!  So if
you think the audio is bad - be grateful that is there at all.

For projection purposes you can also download the slides as a [[file:MPI-Neurology-Talk-Org-mode.pdf][PDF
file]].  If you'd like to prepare your own talk about Org-mode and want
to use (some of) my slides, here is the [[file:MPI-Neurology-Talk-Org-mode-keynote.zip][Apple keynote]] version of the
talk.  The [[file:MPI-Neurology-Talk-Org-mode-ppt.zip][PowerPoint version]] was exported from Keynote and mostly
works. I am making all these files available under the [[http://creativecommons.org/licenses/by/3.0/][creative
commons license]] (attribution).
